
from typing import List
from functools import cmp_to_key

class Solution:
	def rankTeams(self, votes: List[str]) -> str:
		if len(votes) <= 1:
			return votes[0]
		ans = ""
		d = { c: 0 for c in votes[0] }
		for idx in range(len(votes[0])):
			vote = [v[idx] for v in votes]
			for c in vote:
				if c in d:
					d[c] += (len(votes)) ** (len(votes[0]) - idx - 1)
			lst = [[key, d[key]] for key in d.keys()]
			lst = sorted(lst, key = cmp_to_key(lambda x, y: ord(x[0]) - ord(y[0]) if x[1] == y[1] else y[1] - x[1]))
			while len(lst) > 0:
				if len(lst) <= 1 or (len(lst) > 1 and lst[0][1] > lst[1][1]):
					ans += lst[0][0]
					d.pop(lst[0][0])
					lst.pop(0)
				else:
					break
		if len(d.keys()) > 0:
			lst = [[key, d[key]] for key in d.keys()]
			lst = sorted(lst, key = cmp_to_key(lambda x, y: ord(x[0]) - ord(y[0]) if x[1] == y[1] else y[1] - x[1]))
			ans += "".join([c[0] for c in lst])
		return ans


print(Solution().rankTeams(["ABC","ACB","ABC","ACB","ACB"]))
print(Solution().rankTeams(["BCA","CAB","CBA","ABC","ACB","BAC"]))
print(Solution().rankTeams(["WXYZ","XYZW"]))

print(Solution().rankTeams(["FVSHJIEMNGYPTQOURLWCZKAX","AITFQORCEHPVJMXGKSLNZWUY","OTERVXFZUMHNIYSCQAWGPKJL","VMSERIJYLZNWCPQTOKFUHAXG","VNHOZWKQCEFYPSGLAMXJIUTR","ANPHQIJMXCWOSKTYGULFVERZ","RFYUXJEWCKQOMGATHZVILNSP","SCPYUMQJTVEXKRNLIOWGHAFZ","VIKTSJCEYQGLOMPZWAHFXURN","SVJICLXKHQZTFWNPYRGMEUAO","JRCTHYKIGSXPOZLUQAVNEWFM","NGMSWJITREHFZVQCUKXYAPOL","WUXJOQKGNSYLHEZAFIPMRCVT","PKYQIOLXFCRGHZNAMJVUTWES","FERSGNMJVZXWAYLIKCPUQHTO","HPLRIUQMTSGYJVAXWNOCZEKF","JUVWPTEGCOFYSKXNRMHQALIZ","MWPIAZCNSLEYRTHFKQXUOVGJ","EZXLUNFVCMORSIWKTYHJAQPG","HRQNLTKJFIEGMCSXAZPYOVUW","LOHXVYGWRIJMCPSQENUAKTZF","XKUTWPRGHOAQFLVYMJSNEIZC","WTCRQMVKPHOSLGAXZUEFYNJI"]))
# "VWFHSJARNPEMOXLTUKICZGYQ"

print(Solution().rankTeams(["PGAOFXIKYJVSLTUHCZQRE","LSIAPTHYCGURKEZXJOFQV","UGSARZICOXYPHTQFJKVEL","XIAOKSVGRJCHQZUETLYPF","OHRXPGEVUYCSKZILQATFJ","UHFSCZVKIELGOQJYRXPAT","QECXVZKJTLIYHUFRGOSAP","RJGAZIKPEVUSTOXFQYCHL","XRFGPAQSJOETHVCZIKLUY","ZCTQOVRFKXJGEALSHIYUP","QGTEHXCJRIPSUZALOYFVK","GIHXVJPQYOSZFRKLEUTAC","LURXHFECKZSYPTQGAOJVI","TFUKZELVARQCXIYPJHGSO","FIPYTACSXZKLRGOHJVEQU","ZKJQOGHVURAISXFLPYECT","XKOJAHVQUCETFPRYZGLSI","TUKZAVIFXEGQCSOLJRPHY","OSIPCFVRLAYKEHZTJGUQX","OYAQTCEKLGPRZVISUXFHJ","SKHCXEZLTFVQOIUPRAJGY","CRZPAEILFTOKUJVGXHQYS","OQVLPEYZFIGJRKUSXAHTC","VQTXURZKAPGHEIFCOLSJY","YVRZKXSOAEIPUQJHGCFLT","YEJTGFQPOZLCARSUIKVHX","XKASIECRHVQFPULZTOGJY","KAQVYSZLTFXCGEJIRUHOP","IYJXCUTOAPQKHEZFGRVSL","OIEPRLZGUVQHSYJAFTXCK","CIGVAZLKORXQYPHTEUSFJ","UVTCJFQOGXIZHLKYRASEP","FCVOYSJHZLKATXRIUPQGE","TJLQFSRKIUGPCVZHOEAXY","FUHLSRGTCOXAEZVQIYKPJ","CAGRHEUQZISYKXLFVPJOT","LASKUHEPJQXRCTZOVIYFG","IGKJSYLVFCUXETRAHZQPO","UZGXPIAFVOSLKRYQJTCHE","VKELXAFPOGSRIZCUQYTHJ","GCTJEUFRVLKAIOYSHZXQP","PHUOAXLYFTCRSEQIKGJZV","XLQYSIJHTREFPOKCUGVAZ","LUZXHQKIATOCGJYPFSVRE","XILVQZAFUKECYJGTPHSOR","GCQFHJKTAERVPIYUSZOLX","ZPRILGHYXTFVSQCAUKEOJ","SLFTYQPZKUAIVGRHEOCXJ","FCUVEOKHGZQSYJRXPAILT","AKZJRQCPVHYGSXLFITUOE","OKVEHCXPYRUGIAZJQFSLT","YZVHPIGSLREJQCXOKFATU","QTCILUZFVYHSAPGJEKXRO","YXKJOPHIVGARUTZEFLSCQ","OZPXURLHEKFQTSIVJYGCA","YIVEGRJLTPOAZFCQSUXHK","VPQUXLYGACSITFKEJHORZ","AOEQLYPFZUXCKHSTVIJRG","IFYTULEXKZRCOHASQPJGV","TASULVYKZPOCGIHJERXFQ","RGXYZCHVEAPTJISQUFKOL","XKVRTHJSLOZPIAYUEQGFC","EYIRXQTCUPHSVJFZLAKOG","ZRJSTQIGPELKUCHAOYVFX","EIXJPTZGRKVYCUFAOHQLS","LRSGUJZYXCIVQOAHTFPEK","ZHLOESVGIARXCUQYKPFJT","ZKQLVGOIFASTPUHYJRCXE","ZLPJQYTXEGAFHOSRCIUVK","ZVHYQJXCGTAFKLEISOPUR","KZGLYEQAURFHSXIVPTJCO","TIXPAYEKJLVGCQRUHOSZF","ESORYCVXLPKZFQJAUGIHT","FAJTCHORZGLIKXYSVUPQE","AOXHJEZFYLIQCPRVTSGKU","IZVAPOTEHCJQLKRGFUSXY","RTVYZHSIPGCEKJQUAXFOL","GSHOKEXAZCIQYTRJFVLPU","SXZLKIUGEVCPFHTQJARYO","QPCOTHISGLKYJFUAZXVRE","XPUEYATJHCOLVGSQRIZKF","GIKSZFHEQLTCVXJAYOPUR","RFSOEJPUAGKYHZIQCTLXV","UFHXJLITQPEGCKOSZYRAV","ZVQAFGXEIRSTPJYLHCOKU","ZITVJLSOAUGPCFYXHRQKE","RCZOIPEXFJAQGSYVLKHUT","TUHVJROCXIGEPLQAZYKSF","ATQJGKUIPLZXEYCRSOVFH","TVHYLSRAKIXJFGEPOZUCQ","CAPHZLGXQSIRTJYFOKEVU","FAYOKHEUZIRJXQTVGCSPL","IJCRUHVAPFYKGXLTSOQEZ","ZKIJLQEAUVHFTYRXCSGOP","ALFTJSRXUQPIOVZCYHEKG","ZASIVJQYUCRPEKGLTXFHO","OICQXZPEFUSTVALKGYRJH","ZOKVPHUXGRQIJCSEYALFT","FKACPHOSIREGUTYLJXZVQ","IZXOREFGSLPKUHAYCVTJQ","UVXZTCFAQEYLORSKHPJIG","PKVQCYSTLHRZIFAUEXJGO","IRFZSKGEHQVOLXCTJUPAY","XYHPVOTILEAUZJGSKQCRF","ERXJLFZQIGHPCSTYKUVOA","SZTIFCGVEKUJYPAOQXHRL","JPTGQOEYFIKURCVHXALZS","URJGTXZKICAOQSLVEYHFP","ZERGKOLTSUIXJFACVQHPY","GQCVAJYIKRZLTPSFHOUEX","OKRCTSGLZXQJEHPFVYUIA","GUKXARTQFYSCVEZIOJHLP","UTCIRLFHGJOSYZVPQKEAX","JPIOVSFZHUTQKCERXAGLY","LKJEGOHRTYQFXUSCVIPZA","LSETPUAHZYOICVRGJFXKQ","OPGHRVUXQEYLZFISTJKCA","VOKCSGFTXZEIRYALHJPQU","POTXFYCQIVZHLGJERAUSK","FAUIECXOYPLRHJKTSZQVG","XFAETYRCJUGVPQZOKSLHI","LGCVYIAZRFJSHQXTKUOPE","YKATQFIURCHPLSVGJEXOZ","IRUHTAXVYZKFPSEOJCLGQ","TAVEXIHLPOGSZRCJFQKUY","GFACLJSETKIXRZUYHVPOQ","XTJKSAZIQYRCLPGOHUFEV","GSFTZLJCVKRYUOXAQIEPH","GIOLPRXHCSUFKAVTJZEQY","SFCRPVGYKOUZJALQEXHIT","EUTOKQGFCLRAVZPJYSXHI","UOYSHGLTPZXRICFJEKAVQ","OTZIGVXSQHCPRYUKELAJF","SGZOEHLKYUPXCJRFTAVQI","JOCVZLGSUIAHPFKYTQERX","ZFSRJULQGKIOXEPYHTACV","FGSJCIYXHEAZTOLUKRVQP","YXHICZVFTSQJKLPOURGAE","XALRUOHJZYVEGQPKCSFIT","KCIJLRXYHAESGFQUOPVZT","AUTSXLECOGPZIHRVYQKFJ","GIZRAKEVOXLTCJSUHQPFY","ZKUPCORTFYEIAGJQXVLHS","JALHXZQIYSUROPCEGKVFT","KUIGTSQAJEOZYPCFHLXRV","LXICRFZJEUVYASPKQHTOG","EFUPZKRXLCAVJGQITHOSY","EUYGQKARZJVHLIPFCOSTX","AOXTKHRYLJZQEUCSPGVIF","SHUTLZEGRJYPCVAFXQOKI","GUZTAXQLKIRFYEOHJSPVC","RGOZPAXLYVJSHFICKTQUE","ASCHFQVTRLEKYUZIXGJPO","CQFRUSIXLOZPVJTGYAHEK","VGYURSHEXIKCFOAPTQLJZ","VFQCGPEAYISTXKORLUJHZ","UZJOYGVRETFSPLQAIKHCX","JKQRZFXICESTHPGOUYVAL","XGFYRJKCVTESZPHLQUIOA","YEPGFRALQOKJTXSZCIUVH","CXHPFAYKVZQORLJUTEGSI","PXHACSGJUILTYVQRFKEOZ","RSILHFAYCQJKVUGZTPXOE","IKAEOXFVPHSLRCQGZYJTU","GVKRJFLXZUOSAEIYPTCQH","TEXZOUVPICHGFLRYSQKAJ","JCEHLTRZQVFOPUSIKGYXA","GFLJHYXEAQTOPSKIUZVRC","ZGKJFVEAUHIXRTCLSPYQO","GXOTELHIQKUAFSVRPZYCJ","XRZEUGOIVAKSYPHJQCFLT","PYQVXGHSAKLRFTEZOUICJ","QGHOCVKFEPUTSRAIJYZLX","YRQVOLKJGFIXHEPCTUAZS","CTXYFQVZASEHPIOUJGRLK","GIZHRVQLJEYAKTSUCOPXF","XIGKSCLTRYJHZFUOQAPVE","RYCXPSEGIFAULKZTQJVHO","PXEQTGYSHICLAVRUZKJOF","AERXGTIHLUZSFKQYVPCJO","SKTPVFXILUZHYCEJAQROG","OCQUZKSJYLIVARFEHTPGX","ISZXFQUKHJOTCREPGYALV","LOSTQCIRZFVGYKPEAJHUX","QPFTRGUKOIVXESYCJZLAH","PXSUEIVOHZCKJFQLTGRAY","QYLRCVJOPEXGUTZKSAIFH","RJQPOFKXIHUZYVETCSLAG","HTFJEAISYQZUXLCGVPORK","ECGFLAHQJPORITXYUKVZS","FJGAIOSPTVXUZYHLQKERC","GEQLKYPICTUAFRSOVXZHJ","CGJHEZKSTIUQOFVRYXLAP","XYJSGTIKOVUFERLHCPAQZ","LQFVECITUGXHOYJKASRZP","HYGJQFUPZVORSKICLETXA","ACTXZRUYPOJLIEFSKQVGH","PHOLYCFUKRASEGTVQZXIJ","RTUOEZHPSKAFXLQYICVGJ","RAPTGQIJOSEFZUKVXCLHY","EUAKTQLJFOHCPSYVGRZXI","TYUPHSXVEZKIFQACRLJGO","ZHOEAIULSVJQKGRYFTXPC","CPEUIGVRFSOZAKYHQLTJX","ZCOEYRHVQFLSJIXUATGKP","FGSCJZKUTRVOLEYHQIPAX","SPKIGAUVQJXZYEHROCFTL","ITQVPZLEOGJUHKXRYFASC","GSAFTOHJQCYLUVPZEXRKI","ZPFKXLUJSRCAHOGYTVIEQ","QIFYPTAJELCSOXUKRZGVH","JFGZCQAELXKOIUHYRSTVP","TIGPACUOYZJHXKSVQEFRL","EATKLFGOCZVQHXRYSJIPU","SPOJYHVQXGZELUACKFITR","YTVIQXEZUJRFGCOLKSAPH","SPGHEQZJVXKIOAYLRUCFT","RFXCSUZIJAQTELHKVPOGY","PHXJESZRGFLKOAVIQUTYC","GUYCOKILATEJZXHFPRSVQ","GQTUFLAKCPVRYIOHXEZJS","AYVCGFTIQKLZSXEPHRJUO","EAXRUTPZVHCGLISYQFKOJ","SUVFHQGRLXEZAYJTCIPKO","PXKTOGRLHQAJFZCIYUSVE","ZGXYPLOSRCTAVFEUIQKHJ","OKEHXFQSIZGCRJLPATYUV","YXQILGVKPJOUTAZRCSEHF","TYQAGXSCZVKLJEOIHPURF","ELAJZPXRIFQVSGKTOCUHY","YIPXUJHGACTVQEKSOZRLF","ZPAGUYLVSRCIKOJXFTEQH","LYKIJURAEGVZSFPXHCOTQ","EULYFIOJTGXZQCPARHKSV"]))
# "ZGXOEYTSRLIAPFUCQJVKH"

