
"""
# Find the Difference

You are given two strings `s` and `t`.

String `t` is generated by random shuffling string `s` and then add one more letter at a random position.

Return the letter that was added to `t`.


**Example 1:** 
```
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
```

**Example 2:** 
```
Input: s = "", t = "y"
Output: "y"
```

**Constraints:** 
    - `0 <= s.length <= 1000` 
    - `t.length == s.length + 1` 
    - `s` and `t` consist of lowercase English letters.
"""

from collections import Counter
from functools import reduce

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        # # Sorting - O(nlogn) time
        # s, t = sorted(s), sorted(t)
        # for i in range(len(s)):
        #     if s[i] != t[i]:
        #         return t[i]
        # return t[-1]

        # # Count frequency - O(n) time
        # freq_s, freq_t = Counter(s), Counter(t)
        # for c in freq_t:
        #     if freq_t[c] != freq_s[c]:
        #         return c

        # XOR - O(n) time
        return chr(reduce(lambda x, y: x ^ y, map(ord, s + t)))

# e
print(Solution().findTheDifference("abcd", "abcde"))

# y
print(Solution().findTheDifference("", "y"))

# a
print(Solution().findTheDifference("a", "aa"))
